# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cámara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio')),
                ('color', models.CharField(max_length=20)),
                ('weight', models.IntegerField(verbose_name='peso')),
                ('cameraType', models.CharField(choices=[('Digital', 'Digital'), ('Reflex', 'Reflex')], default='Digital', max_length=7, verbose_name='tiposCámara')),
                ('megapixels', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='orden')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio')),
                ('color', models.CharField(max_length=20)),
                ('weight', models.IntegerField(verbose_name='peso')),
                ('processor', models.CharField(max_length=30, verbose_name='procesador')),
                ('ram', models.CharField(max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='orden')),
            ],
        ),
        migrations.CreateModel(
            name='Minicomponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio')),
                ('color', models.CharField(max_length=20)),
                ('weight', models.IntegerField(verbose_name='peso')),
                ('power', models.IntegerField(verbose_name='potencia')),
                ('usb', models.CharField(choices=[('Yes', 'Sí'), ('No', 'No')], default='Yes', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='orden')),
            ],
        ),
    ]
