# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cámara_laptop_minicomponente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cámara',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cámara', to='orders.Order', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop', to='orders.Order', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='minicomponente',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minicomponentes', to='orders.Order', verbose_name='orden'),
        ),
    ]
